services:
  postgresql-users:
    container_name: postgresql-users
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
      PGDATA: /data/postgres
    volumes:
      - postgres-users:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend-network
    restart: unless-stopped

  postgresql-schools:
    container_name: postgresql-schools
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: schools
      PGDATA: /data/postgres
    volumes:
      - postgres-schools:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - backend-network
    restart: unless-stopped

  postgresql-rankings:
    container_name: postgresql-rankings
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rankings
      PGDATA: /data/postgres
    volumes:
      - postgres-rankings:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - backend-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend-network
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - backend-network

  config-server:
    container_name: config-server
    image: rankingDeMaterias/config-server:latest
    environment:
      eureka.instance.hostname: config-server
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/
    ports:
      - "8888:8888"
    networks:
      - backend-network
    depends_on:
      - postgresql-users
      - postgresql-schools
      - postgresql-rankings
    restart: on-failure

  discovery-server:
    container_name: discovery-server
    image: rankingDeMaterias/discovery-server:latest
    ports:
      - "8761:8761"
    networks:
      - backend-network
    depends_on:
      - config-server
    restart: on-failure
    environment:
      eureka.instance.hostname: discovery-server
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

  gateway:
    container_name: gateway
    image: rankingDeMaterias/gateway:latest
    ports:
      - "8222:8222"
    networks:
      - backend-network
    depends_on:
      - config-server
    restart: on-failure
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

  user-service:
    container_name: user-service
    image: rankingDeMaterias/user-service:latest
    ports:
      - "8090:8090"
    networks:
      - backend-network
    depends_on:
      - config-server
      - postgresql-users
    restart: unless-stopped
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

  school-service:
    container_name: school-service
    image: rankingDeMaterias/school-service:latest
    ports:
      - "8070:8070"
    networks:
      - backend-network
    depends_on:
      - config-server
      - postgresql-schools
    restart: on-failure
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

  ranking-service:
    container_name: ranking-service
    image: rankingDeMaterias/ranking-service:latest
    ports:
      - "8100:8100"
    networks:
      - backend-network
    depends_on:
      - config-server
      - postgresql-rankings
    restart: on-failure
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-users:
  postgres-schools:
  postgres-rankings:
  pgadmin:
