eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://user-service:8090
          predicates:
            - Path=/api/v1/users/**
        - id: schools
          uri: http://school-service:8070
          predicates:
            - Path=/api/v1/schools/**
        - id: rankings
          uri: http://ranking-service:8100
          predicates:
            - Path=/api/v1/rankings/**

management:
  tracing:
    sampling:
      probability: 1.0