
export const UNS_MATTERS = {
    "Ingenieria en Sistemas de Informacion": [
        { id: "AM_I", content: "AM I" },
        { id: "OPERATIVOS", content: "OPERATIVOS" },
        { id: "ARQUI_2", content: "ARQUI 2" },
        { id: "EDD", content: "EDD" },
        { id: "REQUE", content: "REQUE" },
        { id: "WEB", content: "WEB" },
        { id: "LFYA", content: "LFYA" },
        { id: "ALGORITMOS", content: "ALGORITMOS" },
        { id: "LOGICA", content: "LOGICA" },
        { id: "TDP", content: "TDP" },
        { id: "TDC", content: "TDC" },
        { id: "BDD", content: "BDD" },
        { id: "ALGEBRA", content: "ALGEBRA" },
        { id: "IPOO", content: "IPOO" },
        { id: "REDES", content: "REDES" },
        { id: "RPA", content: "RPA" },
        { id: "METODOS", content: "METODOS" },
        { id: "MODELOS", content: "MODELOS" },
        { id: "GESTION", content: "GESTION" },
        { id: "VyV", content: "VyV" },
        { id: "ORGA", content: "ORGA" },
        { id: "PSS", content: "PSS" },
        { id: "IIS", content: "IIS" },
        { id: "MECC", content: "MECC" },
        { id: "ARQUI", content: "ARQUI" },
        { id: "QUIMICA", content: "QUIMICA" },
        { id: "ECONOMIA", content: "ECONOMIA" },
        { id: "AM_2", content: "AM 2" },
        { id: "FISICA_II", content: "FISICA II" },
        { id: "PPS", content: "PPS" },
        { id: "Proyecto_Final", content: "Proyecto Final" },
        { id: "Auditorias", content: "Auditorias" },
        { id: "Sistemas_Inteligentes_Artificiales", content: "Sistemas Inteligentes Artificiales" },
        { id: "Fisica_I", content: "Fisica I" },
    ]
};